name: Build

env:
  JVM_VERSION: '21'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - section-1/step-01
          - section-1/step-02
          - section-1/step-03
          - section-1/step-04
          - section-1/step-05
          - section-1/step-06
          - section-1/step-07
          - section-1/step-08
          - section-1/step-09
          - section-1/step-10
          - section-1/step-11
          - section-2/step-01
          - section-2/step-02
          - section-2/step-03
          - section-2/step-04/multi-agent-system
          - section-2/step-04/remote-a2a-agent

    name: "Build ${{ matrix.app }}"
    steps:
      - uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JVM_VERSION }}
          distribution: temurin
          cache: maven
      - name: Maven Build for ${{ matrix.app }}
        working-directory: ${{ matrix.app }}
        run: ./mvnw -B clean verify -Dquarkus.http.host=0.0.0.0 -DskipITs=false


  docs:
    runs-on: ubuntu-latest
    name: "Build Docs"
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - uses: actions/setup-java@v5
        name: Set up Java 21
        with:
          java-version: ${{ env.JVM_VERSION }}
          distribution: temurin
          cache: maven

      - name: Generate documentation
        working-directory: docs
        run: |
          pip install pipenv
          pipenv install
          pipenv run mkdocs build --clean

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
